server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Plonit07/plonit-config
          default-label: main

management:
  endpoint:
    web:
      exposure:
        include: health, busrefresh