server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        # PLONIT
        - id: plonit-service
          uri: lb://PLONIT-SERVICE
          predicates:
            - Path=/plonit-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/plonit-service(?<segment>.*), /$\{segment}
        - id: plonit-service
          uri: lb://PLONIT-SERVICE
          predicates: 
            - Path=/plonit-service/api/**
            - Method=POST, GET, PATCH, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        # FLOGGING
        - id: flogging-service
          uri: lb://FLOGGING-SERVICE
          predicates:
            - Path=/flogging-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/flogging-service(?<segment>.*), /$\{segment}
        - id: flogging-service
          uri: lb://FLOGGING-SERVICE
          predicates:
            - Path=/flogging-service/api/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh